name: integration-test
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]


jobs:
  integration-on-push:
    permissions:
      contents: read
    if: github.event_name == 'push'
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run integration test
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: make integration-test

  integration-on-comment:
    permissions:
        contents: read
        pull-requests: write
    if: contains('Kcrong,resoliwan,SeongIkKim', github.triggering_actor) && contains(github.event.comment.body, '/run integration')
    strategy:
      matrix:
        go: [ stable ]
        os: [ ubuntu-latest ]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run integration test
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: make integration-test
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! I have started the integration test. You can check the status [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            })
